buildImage = 'ghcr.io/railwayapp/nixpacks:latest'

[phases.setup]
  nixpkgsArchive = '11cb3517b3af6af300dd6c055aeda73c9bf52c48'

[phases.build]
  dockerfileLines.before = ["COPY ../../blog.db /app/blog.db"]
